anchor_version = "0.19.0"

[programs.localnet]
anc1 = "6r2DZtptqFkwS1UXPDFioKb8itkaEf6DH4e9pWJdYrLc"

[programs.devnet]
anc1 = "6r2DZtptqFkwS1UXPDFioKb8itkaEf6DH4e9pWJdYrLc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hauwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
